### PR TITLE
ENH: Add tests to the module.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add tests to the module.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
The CI builds will not pass, since the tests are not finished.

@vikramc1 Would you complete the tests?

This will need to be rebased on master after #3 gets merged.

**Comment by thewtex** [comment]
:+1:

**Comment by thewtex** [comment]
Awesome @jhlegarreta !

Could this please be rebased on `master`?

Even without full coverage, we can create an issue to improve the tests, and merge this to get the builds going again.

**Comment by jhlegarreta** [comment]
359e693 rebased on master.

**Comment by jhlegarreta** [comment]
I really did not take the time to looks at the issues of this PR, but now that I look at them, probably the CI failures in the rest of the PRs are related to some of these commits, so thanks @thewtex . This is awesome 👍

**Comment by jhlegarreta** [comment]
The module builds fine now :heavy_check_mark: , but Python packaging seems not to work properly:
```
error: package directory '_skbuild/linux-x86_64-2.7/cmake-install/itk' does not exist 
```

May be we are having issues with the pipeline configuration?

**Comment by thewtex** [comment]
Thanks @jhlegarreta -- even these minimal test caught a few bugs!

@vikramc1 more testing would certainly be helpful ;-).

@jhlegarreta yes, can you please rebase the other branches?

**Comment by jhlegarreta** [comment]
Sure I can. Thanks @thewtex .

**Comment by jhlegarreta** [comment]
>@vikramc1 more testing would certainly be helpful ;-).

@vikramc1 We can definitely help you through.

**Pull request merged**
