### PR TITLE
ENH: Add Python wrapping.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add Python wrapping.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
I'll rebase this on master and solve conflicts when #3 gets merged.

@vikramc1 The Python wrapping of the classes `itk::TimeVaryingVelocityFieldSemiLagrangianIntegrationImageFilter`  and `itk::MetamorphosisImageRegistrationMethodv4` surely requires changes for the wrapping to work properly.

**Comment by thewtex** [comment]
@jhlegarreta could this please be rebased on `master`?

**Comment by jhlegarreta** [comment]
146240c rebased on master.

**Comment by jhlegarreta** [comment]
f302ef2 rebased on master.

**Review by thewtex — APPROVED** [review]

**Comment by jhlegarreta** [comment]
As always, thanks Matt. You rock.

**Pull request merged**
